<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>T7.TableService</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\DiningPhilosophers.Contracts\DiningPhilosophers.Contracts.csproj" />
    </ItemGroup>
    
</Project>
