// <auto-generated />
using System;
using DatabaseSimulation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseSimulation.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20251204093029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.ForkStateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("UsedByPhilosopherId")
                        .HasColumnType("integer");

                    b.Property<string>("UsedByPhilosopherName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId", "TimestampMs");

                    b.HasIndex("SimulationRunId", "ForkId", "TimestampMs");

                    b.ToTable("ForkStateLogs");
                });

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.PhilosopherStateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<int>("EatenCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasLeftFork")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRightFork")
                        .HasColumnType("boolean");

                    b.Property<int>("PhilosopherId")
                        .HasColumnType("integer");

                    b.Property<string>("PhilosopherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId", "TimestampMs");

                    b.HasIndex("SimulationRunId", "PhilosopherId", "TimestampMs");

                    b.ToTable("PhilosopherStateLogs");
                });

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhilosopherCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.ForkStateLog", b =>
                {
                    b.HasOne("DatabaseSimulation.Data.Entities.SimulationRun", "SimulationRun")
                        .WithMany("ForkStateLogs")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.PhilosopherStateLog", b =>
                {
                    b.HasOne("DatabaseSimulation.Data.Entities.SimulationRun", "SimulationRun")
                        .WithMany("PhilosopherStateLogs")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("DatabaseSimulation.Data.Entities.SimulationRun", b =>
                {
                    b.Navigation("ForkStateLogs");

                    b.Navigation("PhilosopherStateLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
